### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/RPr-Chakraborty-2021#6]
We need to create metadata for each of the data layers in the repository. 

One good tool for creating metadata documents is: https://github.com/usgs/fort-pymdwizard/releases 

It is also possible to download data dictionaries for American Community Survey tables, and hopefully some documentation from the Johns Hopkins Coronavirus Center.

Once any metadata files are downloaded into the metadata folder, add the names of those files to the relevant row of the data_metadata.csv file.

**Comment by josephholler** [comment]
Update: we have the data dictionaries downloaded. 
The other options for editing metdata are https://go.mdeditor.org (web-based interface) and https://geonetwork-opensource.org/ (a little catalogue server you would need to install)

**Comment by josephholler** [comment]
Sources of info for use constraints on Census Data: https://www.census.gov/data/developers/about/terms-of-service.html 

Use constraints on Johns hopkins data (see terms of service tab at bottom right): https://coronavirus.jhu.edu/map.html

**Comment by josephholler** [comment]
Access constraints are usually the LICENSE for the data

**Comment by emilyzhou112** [comment]
The metadata files have been created and uploaded to the repository.
