### ISSUE TITLE
GEE comparison table

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/RPr-Chakraborty-2021#8]
I previously mocked up a table in Excel, and just moved it to Results/Tables. The reproduction numbers are for a previous version of the code, prior to implementing the z-score normalization.

Since we already talked about making a table like this, can we update the data to match the current model?

**Comment by emilyzhou112** [comment]
The z-score normalization has been implemented on the independent variables and the GEE comparison table has been updated.
