### ISSUE TITLE
Cluster-based relative risk score

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/RPr-Chakraborty-2021#9]
The SpatialEpi package in R does not calculate relative risk. In our code thus far, we have calculated **local** relative risk for each county. It would be better to calculate **cluster** relative risk as `incidence within cluster` / `incidence outside of cluster` 

where `incidence within cluster` = `sum of cases within cluster` / `sum of population within cluster`

and

`incidence outside of cluster` = (`total of all cases` - `sum of cases within cluster`) / (`total of all population` - `sum of population within cluster`)

This cluster rate would be calculated once for each cluster. Then to map this by county, it would be necessary to find the maximum cluster rate for each county. This would be easiest to achieve if a long table of counties was generated with three columns: county id, cluster id, and cluster relative risk. As the results of each cluster are found, they are appended to the table, such that some counties will have more than one row in the table if they are overlapped by more than one cluster. Once this long table is created, it can be grouped by county to find the maximum.

**Comment by emilyzhou112** [comment]
Draft code in progress:)
Based on the output of the spatial scan, it does not look like that there are any counties overlapped by more than one cluster…

**Comment by josephholler** [comment]
Completed by Emily. Thanks!
